import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultText?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Brand & Header
    'brand.title': 'Waimao Tools',
    'brand.subtitle': 'Foreign Trade & Export',
    'header.search_placeholder': 'Search invoices, clients, products...',
    'header.exchange_rate': '1 USD = ¥7.25',
    'header.new_document': 'New Document',
    'header.calculator': 'Calculator',
    'header.cloud_sync': 'Cloud Sync',
    'header.firestore_live': 'Firestore Live Sync',
    'header.user_profile': 'User Profile',
    'header.verified_account': 'Verified Google Account',
    'header.logout': 'Sign Out',
    'header.view_profile': 'View & Edit Profile',
    'header.rate_tooltip': 'Click to open Quotation & Price Calculator',
    
    // Quick New Document Menu
    'menu.new_invoice': 'Commercial Invoice',
    'menu.new_packing': 'Packing List',
    'menu.new_quotation': 'Sales Quotation',
    'menu.new_proforma': 'Proforma Invoice (PI)',
    'menu.new_contract': 'Sales Contract (SC)',
    'menu.new_sample': 'Sample Invoice',
    'menu.new_calculator': 'Quotation Cost Calculator',

    // Sidebar navigation
    'nav.home': 'Home & Features',
    'nav.dashboard': 'Dashboard',
    'nav.quotation_calculator': 'Quotation Calculator',
    'nav.invoice': 'Commercial Invoice',
    'nav.proforma': 'Proforma Invoice',
    'nav.quotation': 'Price Quotation',
    'nav.packing': 'Packing List Gen',
    'nav.contract': 'Sales Contract',
    'nav.certificate': 'Certificate of Origin',
    'nav.shipping': 'Shipping Instructions',
    'nav.sample': 'Sample Invoice',
    'nav.cbm_calculator': 'Container CBM Calc',
    'nav.products': 'Product Library',
    'nav.clients': 'Client Database',
    'nav.settings': 'Company Settings',
    'nav.tools_all': 'All Tools',
    'nav.overview': 'Overview',
    'nav.invoices': 'Invoices',
    'nav.calculator': 'Calculator',
    'nav.products_short': 'Products',

    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': 'Trade & Export Document Suite — Real-time Firestore synchronizing across devices',
    'dashboard.overview': 'Dashboard Overview',
    'dashboard.welcome_workspace': 'Welcome to Waimao Tools Workspace.',
    'dashboard.new_invoice': 'New Invoice',
    'dashboard.commercial_value': 'Commercial Value',
    'dashboard.active_ledger': 'Active ledger summary value',
    'dashboard.library_catalog': 'Library Catalog',
    'dashboard.stored_skus': 'Stored export product SKUs',
    'dashboard.packing_ledgers': 'Packing Ledgers',
    'dashboard.active_shipment_pls': 'Active shipment packing lists',
    'dashboard.sample_logs': 'Sample Logs',
    'dashboard.free_samples_count': 'Free evaluations supplied',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.new_ci_title': 'New Commercial Invoice',
    'dashboard.new_ci_desc': 'Commercial exporting billing',
    'dashboard.new_pl_title': 'New Packing List',
    'dashboard.new_pl_desc': 'Container freight specs sheet',
    'dashboard.calc_title': 'Quotation Calculator',
    'dashboard.calc_desc': 'Inquiry cost, dip tube, color & FOB',
    'dashboard.new_sample_title': 'New Sample Invoice',
    'dashboard.new_sample_desc': 'Free items & courier tracking',
    'dashboard.settings_title': 'Company Settings',
    'dashboard.settings_desc': 'Configure stamps, logos, bank info',
    'dashboard.recent_ledger': 'Recent Unified Ledger',
    'dashboard.last_entries': 'Last 5 active entries',
    'dashboard.no_docs': 'No generated documents yet. Tap any quick action above to start.',
    'dashboard.view_print': 'View / Print',
    'dashboard.insights_title': 'Export & Trade Insights',
    'dashboard.hs_code_title': 'Verified HS Codes',
    'dashboard.hs_code_desc': 'Standardized exporter codes: 3924.10, 3923.10 loaded in database.',
    'dashboard.company_conf_title': 'Company Settings Configured',
    'dashboard.company_conf_desc': 'Stamps, swift details, default VAT (14%) are ready and auto-fill documents.',
    'dashboard.a4_title': 'A4 Formatting Standard',
    'dashboard.a4_desc': 'A4 document exports are fully responsive, clean layout and ready to download.',
    'dashboard.exporter_tip': 'Exporter Tip: When compiling Invoices or Packing Lists, click "Select from Product Library" or "Select Client" to automatically pull weights, dimension specs, barcodes, and address logs!',
    'dashboard.total_invoiced': 'Total Commercial Invoiced',
    'dashboard.active_clients': 'Active Global Clients',
    'dashboard.products_catalog': 'Products in Catalog',
    'dashboard.sales_contracts': 'Executed Sales Contracts',
    'dashboard.recent_activity': 'Recent Documents & Ledger',
    'dashboard.no_recent': 'No documents created yet. Start by generating an invoice or adding a product.',
    'dashboard.doc_number': 'Document No.',
    'dashboard.doc_type': 'Type',
    'dashboard.client': 'Client / Buyer',
    'dashboard.amount': 'Amount',
    'dashboard.date': 'Date',
    'dashboard.actions': 'Actions',
    'dashboard.view_edit': 'View / Edit',

    // Cloud Sync Badge
    'sync.syncing': 'Syncing Cloud...',
    'sync.synced': 'Firestore Live Sync',
    'sync.error': 'Cloud Sync Issue',
    'sync.offline': 'Local Offline Cache',
    'sync.title': 'Cloud Firestore Database',
    'sync.desc': 'Single Source of Truth across all devices',
    'sync.cross_device': 'Cross-Device Sync: Changes on Computer, iPad, or Mobile update instantly.',
    'sync.google_account': 'Google Account',
    'sync.account_uid': 'Account UID',
    'sync.last_sync': 'Last Sync',
    'sync.force_refresh': 'Refresh Cloud',
    'sync.security_rules': 'Security Rules Enforced',

    // Auth Page
    'auth.title': 'Waimao International Trade',
    'auth.subtitle': 'Cloud-Synchronized Foreign Trade Management Suite',
    'auth.continue_google': 'Continue with Google Account',
    'auth.or_email': 'or sign in with email',
    'auth.email_label': 'Business Email Address',
    'auth.password_label': 'Password',
    'auth.company_label': 'Company / Enterprise Name',
    'auth.name_label': 'Full Name / Contact Person',
    'auth.login_tab': 'Sign In',
    'auth.register_tab': 'Create Account',
    'auth.signin_button': 'Sign In to Workspace',
    'auth.register_button': 'Create Trade Workspace',
    'auth.switch_register': "Don't have an account? Register now",
    'auth.switch_login': 'Already have an account? Sign in',
    'auth.feature_cloud': 'Real-time multi-device cloud synchronization',
    'auth.feature_security': 'Zero data loss with Firestore security isolation',
    'auth.feature_docs': 'Proforma, Invoices, Contracts, Quotations & CBM Calc',

    // Modals, Guards & Popups
    'modal.unsaved_title': 'Unsaved Changes Detected',
    'modal.unsaved_subtitle': 'Save your progress before exiting or navigating away',
    'modal.unsaved_desc': 'You have active unsaved modifications. If you exit now without saving, any uncommitted changes will be permanently discarded.',
    'modal.unsaved_question': 'Would you like to save your data now before leaving?',
    'modal.keep_editing': 'Keep Editing',
    'modal.discard_exit': 'Discard & Exit',
    'modal.save_continue': 'Save & Continue',
    'modal.saving_data': 'Saving Data...',
    'modal.img_title': 'Product Image Manager',
    'modal.img_upload_tab': 'Upload File / Paste (Ctrl+V)',
    'modal.img_preset_tab': 'Preset Vector Library',
    'modal.img_url_tab': 'Web URL Link',
    'modal.img_drag_text': 'Click to browse or drag & drop product photo',
    'modal.img_supports': 'Supports JPG, PNG, WEBP, SVG or GIF. You can also paste from clipboard (Ctrl + V).',
    'modal.img_select_btn': 'Select File from Computer',
    'modal.img_remove_bg': 'Remove White BG',
    'modal.img_remove_photo': 'Remove Image',
    'modal.img_apply_btn': 'Apply Product Image',

    // Products Library
    'products.title': 'Product & Components Catalog',
    'products.subtitle': 'Manage export product specifications, factory master prices, packaging metrics, HS codes and high-res vector graphics.',
    'products.new_product': 'Add New Product',
    'products.import_csv': 'Import CSV',
    'products.export_csv': 'Export CSV',
    'products.total_skus': 'Total Registered SKUs',
    'products.categories': 'Active Categories',
    'products.avg_carton_cbm': 'Avg Carton CBM',
    'products.search_placeholder': 'Search product name, SKU, category, material...',
    'products.all_categories': 'All Categories',
    'products.filter_category': 'Filter Category',
    'products.card_view': 'Grid Cards',
    'products.table_view': 'Dense Table',
    'products.edit_spec': 'Edit Spec',
    'products.clone_sku': 'Clone SKU',
    'products.delete_sku': 'Delete SKU',
    'products.no_products_found': 'No products matching your search query.',
    'products.basic_info': 'Basic Information',
    'products.pricing_moq': 'Pricing, MOQ & Packaging',
    'products.dimensions_weights': 'Carton Dimensions & Weights',
    'products.product_name': 'Product Name / Description',
    'products.sku_code': 'Item Model / SKU Code',
    'products.category': 'Product Category',
    'products.material': 'Raw Material / Construction',
    'products.color': 'Color / Surface Finish',
    'products.hs_code': 'Customs HS Code',
    'products.unit_price': 'FOB / Factory Unit Price',
    'products.currency': 'Currency',
    'products.moq': 'Minimum Order Qty (MOQ)',
    'products.pcs_per_box': 'Pieces Per Master Carton',
    'products.carton_length': 'Carton Length (cm)',
    'products.carton_width': 'Carton Width (cm)',
    'products.carton_height': 'Carton Height (cm)',
    'products.gross_weight': 'Carton Gross Weight (kg)',
    'products.net_weight': 'Carton Net Weight (kg)',
    'products.item_unit_weight': 'Individual Item Net Weight (kg)',
    'products.cbm_per_carton': 'Carton CBM (m³)',
    'products.save_specs': 'Save Product Specifications',
    'products.cancel_edit': 'Cancel',

    // Clients Database
    'clients.title': 'Client & Buyer Database',
    'clients.subtitle': 'Maintain directories of international shipping agents, distributors, and global buyers.',
    'clients.new_client': 'Add New Client',
    'clients.search_placeholder': 'Search company name, contact person, country or email...',
    'clients.total_clients': 'Total Registered Buyers',
    'clients.company_name': 'Company Name',
    'clients.contact_person': 'Contact Person / Agent',
    'clients.country': 'Country / Territory',
    'clients.email': 'Email Address',
    'clients.phone': 'Phone / WhatsApp',
    'clients.address': 'Billing & Delivery Address',
    'clients.notes': 'Client Notes / Payment Terms',
    'clients.save_client': 'Save Client Profile',
    'clients.no_clients': 'No clients recorded yet.',

    // Quotation & Price Calculator
    'calc.title': 'Quotation & Export Cost Calculator',
    'calc.subtitle': 'Simulate unit FOB/CIF prices, component add-ons (dip tubes, colors, hot stamping, UV plating), freight allocations & tier margin simulations.',
    'calc.new_calc': 'New Quotation Calc',
    'calc.search_placeholder': 'Search calculations, buyer, products...',
    'calc.base_product': 'Base Product & Specs',
    'calc.select_product': 'Select from Product Library',
    'calc.select_client': 'Select Client / Buyer',
    'calc.factory_cost': 'Factory Ex-Work Cost (RMB)',
    'calc.exchange_rate': 'USD/RMB Exchange Rate',
    'calc.tax_rebate': 'VAT Export Rebate Rate (%)',
    'calc.profit_margin': 'Target Profit Margin (%)',
    'calc.domestic_freight': 'Domestic Port Freight (RMB)',
    'calc.port_charges': 'Port Surcharge & Docs (RMB)',
    'calc.ocean_freight': 'Ocean / Air Freight (USD)',
    'calc.moq_tiers': 'Quantity Tier Pricing Table',
    'calc.qty_tier': 'Order Qty Tier (pcs)',
    'calc.fob_price': 'Final Unit FOB Price',
    'calc.cif_price': 'Final Unit CIF Price',
    'calc.total_profit': 'Projected Gross Margin',
    'calc.convert_to_quotation': 'Generate Quotation PDF',
    'calc.convert_to_pi': 'Convert into Proforma (PI)',
    'calc.convert_to_ci': 'Convert into Invoice (CI)',

    // CBM & Container Loading Calculator
    'cbm.title': 'Container CBM & Packing Calculator',
    'cbm.subtitle': 'Calculate cargo cubic meters (CBM), gross weight (KG), and simulate full container load (FCL) packing efficiency.',
    'cbm.add_item': 'Add Cargo Line',
    'cbm.select_preset': 'Add from Product Library',
    'cbm.total_cbm': 'Total Volume (CBM)',
    'cbm.total_weight': 'Total Gross Weight (KG)',
    'cbm.total_cartons': 'Total Master Cartons',
    'cbm.total_pcs': 'Total Cargo Units (PCS)',
    'cbm.container_fit': 'Container Utilization Analysis',
    'cbm.fit_status': 'Loading Feasibility',
    'cbm.create_invoice': 'Generate Commercial Invoice from CBM',
    'cbm.create_packing': 'Generate Packing List from CBM',

    // Document Shared (Toolbar, Ledger & Editor)
    'doc.ledger_title': 'Document Ledger & Archives',
    'doc.create_new': 'Create New Draft',
    'doc.edit_doc': 'Edit Document',
    'doc.print_pdf': 'Print / Export PDF',
    'doc.download_pdf': 'Download PDF',
    'doc.save_sync': 'Save & Sync Cloud',
    'doc.delete_doc': 'Delete Document',
    'doc.back_to_list': 'Back to Document List',
    'doc.basic_details': 'Document Details & Reference',
    'doc.invoice_number': 'Invoice No.',
    'doc.document_date': 'Issue Date',
    'doc.due_date': 'Due Date',
    'doc.payment_terms': 'Payment Terms',
    'doc.delivery_terms': 'Incoterms / Delivery',
    'doc.currency': 'Invoice Currency',
    'doc.seller_info': 'Shipper / Exporter Details',
    'doc.buyer_info': 'Consignee / Buyer Details',
    'doc.items_table': 'Product Line Items',
    'doc.item_desc': 'Description of Goods',
    'doc.item_sku': 'Item / SKU',
    'doc.item_qty': 'Quantity',
    'doc.item_unit': 'Unit',
    'doc.item_unit_price': 'Unit Price',
    'doc.item_total': 'Total Amount',
    'doc.subtotal': 'Subtotal Amount',
    'doc.shipping_fee': 'Freight / Shipping Fee',
    'doc.insurance_fee': 'Insurance Charge',
    'doc.packaging_fee': 'Packaging Charge',
    'doc.discount': 'Trade Discount',
    'doc.grand_total': 'Grand Total Amount',
    'doc.notes_terms': 'Special Remarks & Banking Instructions',
    'doc.bank_details': 'Wire Transfer / SWIFT Instructions',
    'doc.stamp_sign': 'Company Official Seal & Signature',
    'doc.copy_btn': 'Duplicate Document',

    // Specific Documents
    'doc.ci_title': 'Commercial Invoice (CI)',
    'doc.ci_desc': 'Generate standard customs commercial invoices with automated currency formatting and bank profiles.',
    'doc.pi_title': 'Proforma Invoice (PI)',
    'doc.pi_desc': 'Create sales proforma invoices for deposit collection and international purchase orders.',
    'doc.quotation_title': 'Price Quotation Sheet',
    'doc.quotation_desc': 'Formal export sales quotation sheets with quantity breakdown, validities, and shipping terms.',
    'doc.packing_title': 'Packing List (PL)',
    'doc.packing_desc': 'Detailed shipment packing breakdown with net/gross weights, carton measurements, and total CBM.',
    'doc.contract_title': 'International Sales Contract',
    'doc.contract_desc': 'Bilingual export sales contract with standard legal arbitration, dispute resolution, and force majeure clauses.',
    'doc.co_title': 'Certificate of Origin (CO)',
    'doc.co_desc': 'Standard Generalized System of Preferences / Chamber of Commerce Certificate of Origin.',
    'doc.shipping_title': 'Shipping Instructions & Booking',
    'doc.shipping_desc': 'Forwarder booking note and shipping instruction draft with vessel, voyage, and notify party.',
    'doc.sample_title': 'Sample Commercial Invoice',
    'doc.sample_desc': 'Zero-value / evaluation sample invoice for express DHL, FedEx, UPS customs clearance.',

    // Company Settings
    'settings.title': 'Company & Export Profile Settings',
    'settings.subtitle': 'Manage your export entity details, banking instructions, company seal stamp, and signatures.',
    'settings.save_success': 'Settings successfully saved and synchronized to Cloud Firestore!',
    'settings.company_name': 'Company Legal Name (English)',
    'settings.company_address': 'Registered Business Address',
    'settings.tax_id': 'Tax ID / USCC (统一社会信用代码)',
    'settings.phone': 'Contact Telephone',
    'settings.email': 'Official Email',
    'settings.website': 'Website URL',
    'settings.bank_info': 'International Banking Instructions',
    'settings.bank_name': 'Beneficiary Bank Name',
    'settings.account_name': 'Account Holder Name',
    'settings.account_num': 'Account / IBAN Number',
    'settings.swift_code': 'SWIFT / BIC Code',
    'settings.bank_branch': 'Bank Branch & Address',
    'settings.seal_signature': 'Official Company Stamp & Signature',
    'settings.stamp_label': 'Company Export Stamp (Seal)',
    'settings.signature_label': 'Authorized Signature',
    'settings.save_button': 'Save & Sync Settings',
    'settings.reset_workspace': 'Reset Workspace Data',

    // Common Buttons & Tooltips
    'btn.save': 'Save',
    'btn.cancel': 'Cancel',
    'btn.delete': 'Delete',
    'btn.edit': 'Edit',
    'btn.create': 'Create New',
    'btn.print': 'Print / Export PDF',
    'btn.download_pdf': 'Download PDF',
    'btn.add_item': 'Add Line Item',
    'btn.search': 'Search',
    'btn.filter': 'Filter',
    'btn.close': 'Close',
    'btn.back': 'Back',
    'btn.confirm': 'Confirm',
    'btn.copy': 'Copy',
    'btn.copied': 'Copied!',
    'btn.export': 'Export',
    'btn.import': 'Import',
    'btn.refresh': 'Refresh',

    // Languages
    'lang.english': 'English',
    'lang.chinese': '中文 (简体)'
  },
  zh: {
    // Brand & Header
    'brand.title': '外贸百宝箱',
    'brand.subtitle': '外贸单证与报价管理系统',
    'header.search_placeholder': '搜索发票、客户、产品、单据...',
    'header.exchange_rate': '1 美元 = 7.25 人民币',
    'header.new_document': '新建单据',
    'header.calculator': '报价核算',
    'header.cloud_sync': '云端同步',
    'header.firestore_live': 'Firestore 实时云同步',
    'header.user_profile': '个人中心',
    'header.verified_account': '已验证谷歌账号',
    'header.logout': '退出登录',
    'header.view_profile': '查看与修改公司信息',
    'header.rate_tooltip': '点击打开外贸报价与利润核算器',

    // Quick New Document Menu
    'menu.new_invoice': '商业发票 (Commercial Invoice)',
    'menu.new_packing': '装箱单 (Packing List)',
    'menu.new_quotation': '报价单 (Sales Quotation)',
    'menu.new_proforma': '形式发票 (Proforma Invoice / PI)',
    'menu.new_contract': '外贸售货合同 (Sales Contract / SC)',
    'menu.new_sample': '免费/样品发票 (Sample Invoice)',
    'menu.new_calculator': 'FOB/CIF 成本与利润核算器',

    // Sidebar navigation
    'nav.home': '首页与功能详解',
    'nav.dashboard': '工作台总览',
    'nav.quotation_calculator': '报价与利润核算',
    'nav.invoice': '商业发票 (CI)',
    'nav.proforma': '形式发票 (PI)',
    'nav.quotation': '外贸报价单',
    'nav.packing': '装箱单生成器',
    'nav.contract': '外贸售货合同',
    'nav.certificate': '原产地证明书 (CO)',
    'nav.shipping': '装运通知 / 订舱单',
    'nav.sample': '免费样品发票',
    'nav.cbm_calculator': '集装箱装柜计算 (CBM)',
    'nav.products': '出口产品目录库',
    'nav.clients': '全球买家客户库',
    'nav.settings': '公司抬头与印章设置',
    'nav.tools_all': '全部工具',
    'nav.overview': '总览',
    'nav.invoices': '单据发票',
    'nav.calculator': '报价核算',
    'nav.products_short': '产品库',

    // Dashboard
    'dashboard.welcome': '欢迎回来',
    'dashboard.subtitle': '一站式外贸全流程单证生成系统 — Firestore 云端多设备实时秒级同步',
    'dashboard.overview': '工作台总览概况',
    'dashboard.welcome_workspace': '欢迎使用外贸百宝箱工作台。',
    'dashboard.new_invoice': '新建商业发票',
    'dashboard.commercial_value': '商业发票总金额',
    'dashboard.active_ledger': '当前台账累计总值',
    'dashboard.library_catalog': '出口产品目录库',
    'dashboard.stored_skus': '已登记在库产品 SKU',
    'dashboard.packing_ledgers': '出运装箱单台账',
    'dashboard.active_shipment_pls': '出运装柜装箱单',
    'dashboard.sample_logs': '免费样品发票台账',
    'dashboard.free_samples_count': '寄送样品与测试品',
    'dashboard.quick_actions': '快捷操作与新建',
    'dashboard.new_ci_title': '新建商业发票 (CI)',
    'dashboard.new_ci_desc': '出口报关结汇收款发票',
    'dashboard.new_pl_title': '新建装箱单 (PL)',
    'dashboard.new_pl_desc': '集装箱毛重净重立方清单',
    'dashboard.calc_title': '外贸报价与利润核算器',
    'dashboard.calc_desc': '询盘成本、汇率、FOB/CIF 测算',
    'dashboard.new_sample_title': '新建样品发票',
    'dashboard.new_sample_desc': '免费样品与快递运单跟踪',
    'dashboard.settings_title': '公司抬头与印章设置',
    'dashboard.settings_desc': '配置中英文公章、银行信息与签名',
    'dashboard.recent_ledger': '最新单据台账总览',
    'dashboard.last_entries': '最近 5 条动态记录',
    'dashboard.no_docs': '暂无单据记录。点击上方快捷按钮即可立即开始制单。',
    'dashboard.view_print': '查看 / 打印',
    'dashboard.insights_title': '外贸出口合规与业务提示',
    'dashboard.hs_code_title': '标准海关 HS 编码验证',
    'dashboard.hs_code_desc': '系统已预置标准化商品海关编码：3924.10, 3923.10 等快速调用。',
    'dashboard.company_conf_title': '公司出海档案已配置',
    'dashboard.company_conf_desc': '中英文公章、SWIFT 银行收汇信息、退税率已生效并自动套入单据。',
    'dashboard.a4_title': '国际 A4 标准排版',
    'dashboard.a4_desc': '所有单据均支持一键生成高清 A4 打印与 PDF 下载，格式完全合规。',
    'dashboard.exporter_tip': '外贸小贴士：制作商业发票或装箱单时，点击“从产品库导入”或“选择客户”，系统将自动带出净重、毛重、外箱尺寸、条码及客户完整地址！',
    'dashboard.total_invoiced': '已开商业发票总额',
    'dashboard.active_clients': '全球合作买家客户',
    'dashboard.products_catalog': '在库外贸出口产品',
    'dashboard.sales_contracts': '已签署外贸合同',
    'dashboard.recent_activity': '最新单据台账记录',
    'dashboard.no_recent': '暂无单据记录。点击上方快捷按钮即可立即生成商业发票或添加产品。',
    'dashboard.doc_number': '单据编号',
    'dashboard.doc_type': '单据类型',
    'dashboard.client': '买家/客户公司',
    'dashboard.amount': '金额',
    'dashboard.date': '制单日期',
    'dashboard.actions': '操作',
    'dashboard.view_edit': '查看 / 编辑',

    // Cloud Sync Badge
    'sync.syncing': '正在同步云端...',
    'sync.synced': 'Firestore 实时云同步',
    'sync.error': '云端同步异常',
    'sync.offline': '本地离线缓存',
    'sync.title': 'Cloud Firestore 云数据库',
    'sync.desc': '所有设备间单一真实数据源 (Single Source of Truth)',
    'sync.cross_device': '多设备无缝同步：电脑、iPad 或手机端修改实时生效。',
    'sync.google_account': '当前 Google 账号',
    'sync.account_uid': '账号专属 UID',
    'sync.last_sync': '最近同步时间',
    'sync.force_refresh': '立即刷新云端',
    'sync.security_rules': '安全规则已严格隔离',

    // Auth Page
    'auth.title': '外贸百宝箱 Waimao Tools',
    'auth.subtitle': '专业外贸单证与出口业务多端云协同管理平台',
    'auth.continue_google': '使用 Google 谷歌账号一键登录',
    'auth.or_email': '或使用企业邮箱登录',
    'auth.email_label': '企业邮箱地址',
    'auth.password_label': '登录密码',
    'auth.company_label': '外贸公司/工厂英文名称',
    'auth.name_label': '业务员姓名 / 联系人',
    'auth.login_tab': '账号登录',
    'auth.register_tab': '注册新账号',
    'auth.signin_button': '登 录 工 作 台',
    'auth.register_button': '立即创建外贸工作空间',
    'auth.switch_register': '还没有账号？立即免费注册',
    'auth.switch_login': '已有账号？直接登录',
    'auth.feature_cloud': '电脑、平板、手机多端秒级实时自动同步',
    'auth.feature_security': 'Google 安全认证与 Firestore 账户级隔离',
    'auth.feature_docs': 'PI、CI、装箱单、合同、原产地证一键极速制单',

    // Modals, Guards & Popups
    'modal.unsaved_title': '检测到未保存的数据更改',
    'modal.unsaved_subtitle': '在离开或切换页面前，请保存您的单据内容',
    'modal.unsaved_desc': '您当前有正在编辑但未提交的内容。如果直接退出，所有未保存的修改将被永久丢弃。',
    'modal.unsaved_question': '您是否需要在离开前立即保存数据？',
    'modal.keep_editing': '继续编辑',
    'modal.discard_exit': '放弃并离开',
    'modal.save_continue': '保存并继续',
    'modal.saving_data': '正在保存数据...',
    'modal.img_title': '产品图片管理',
    'modal.img_upload_tab': '上传本地图片 / 剪贴板粘贴 (Ctrl+V)',
    'modal.img_preset_tab': '工厂矢量图库',
    'modal.img_url_tab': '网络图片链接',
    'modal.img_drag_text': '点击选择文件或将产品图片拖拽到此处',
    'modal.img_supports': '支持 JPG, PNG, WEBP, SVG 或 GIF 格式。亦可直接截图后粘贴 (Ctrl + V)。',
    'modal.img_select_btn': '从电脑选择图片',
    'modal.img_remove_bg': '智能一键去除白底',
    'modal.img_remove_photo': '移除图片',
    'modal.img_apply_btn': '应用产品图片',

    // Products Library
    'products.title': '出口产品与配件目录库',
    'products.subtitle': '集中管理出口产品规格参数、工厂出厂底价、装箱外箱参数、海关 HS 编码及高清产品图片。',
    'products.new_product': '添加新产品',
    'products.import_csv': '导入 CSV',
    'products.export_csv': '导出 CSV',
    'products.total_skus': '在库登记产品总数',
    'products.categories': '现有产品分类',
    'products.avg_carton_cbm': '平均外箱体积 (CBM)',
    'products.search_placeholder': '搜索产品名称、型号 SKU、分类、材质...',
    'products.all_categories': '全部分类',
    'products.filter_category': '筛选分类',
    'products.card_view': '图文卡片',
    'products.table_view': '表格视图',
    'products.edit_spec': '编辑规格',
    'products.clone_sku': '复制 SKU',
    'products.delete_sku': '删除产品',
    'products.no_products_found': '没有找到符合条件的产品。',
    'products.basic_info': '产品基本信息',
    'products.pricing_moq': '价格、起订量与装箱率',
    'products.dimensions_weights': '外箱尺寸与重量参数',
    'products.product_name': '产品英文名称 / 描述',
    'products.sku_code': '产品型号 / SKU',
    'products.category': '所属分类',
    'products.material': '制造材质 / 工艺',
    'products.color': '外观颜色 / 表面处理',
    'products.hs_code': '海关 HS 编码',
    'products.unit_price': 'FOB / 工厂单价',
    'products.currency': '币种',
    'products.moq': '最小起订量 (MOQ)',
    'products.pcs_per_box': '单箱装箱数量 (PCS/CTN)',
    'products.carton_length': '外箱长 (cm)',
    'products.carton_width': '外箱宽 (cm)',
    'products.carton_height': '外箱高 (cm)',
    'products.gross_weight': '单箱毛重 (kg)',
    'products.net_weight': '单箱净重 (kg)',
    'products.item_unit_weight': '单只产品净重 (kg)',
    'products.cbm_per_carton': '单箱体积 (m³)',
    'products.save_specs': '保存产品档案',
    'products.cancel_edit': '取消',

    // Clients Database
    'clients.title': '全球买家与客户档案库',
    'clients.subtitle': '系统化管理海外采购商、货代货运代理、品牌商及分销商完整联络信息。',
    'clients.new_client': '添加新客户',
    'clients.search_placeholder': '搜索客户公司、联系人、国家或邮箱...',
    'clients.total_clients': '已建档买家总数',
    'clients.company_name': '买家公司名称',
    'clients.contact_person': '主要联系人 / 采购代理',
    'clients.country': '国家 / 地区',
    'clients.email': '电子邮箱',
    'clients.phone': '联系电话 / WhatsApp',
    'clients.address': '账单及货物送达地址',
    'clients.notes': '客户备注 / 付款习惯',
    'clients.save_client': '保存客户资料',
    'clients.no_clients': '暂无已登记的客户记录。',

    // Quotation & Price Calculator
    'calc.title': '外贸报价与出口成本核算器',
    'calc.subtitle': '精确测算 FOB/CIF 单价、配件加价（长管、电化铝、定制颜色、丝印打标）、运杂费分摊及各起订量阶梯利润率。',
    'calc.new_calc': '新建报价测算',
    'calc.search_placeholder': '搜索历史测算、买家名称、产品型号...',
    'calc.base_product': '基础产品与规格',
    'calc.select_product': '从产品库选择产品',
    'calc.select_client': '选择目标客户 / 买家',
    'calc.factory_cost': '工厂含税出厂成本 (RMB)',
    'calc.exchange_rate': '美金兑人民币汇率',
    'calc.tax_rebate': '出口退税率 (%)',
    'calc.profit_margin': '目标利润率 (%)',
    'calc.domestic_freight': '国内港口运杂费 (RMB)',
    'calc.port_charges': '码头杂费与报关费 (RMB)',
    'calc.ocean_freight': '海运 / 空运国际运费 (USD)',
    'calc.moq_tiers': '数量阶梯报价模拟表',
    'calc.qty_tier': '起订量阶梯 (pcs)',
    'calc.fob_price': '最终建议 FOB 单价',
    'calc.cif_price': '最终建议 CIF 单价',
    'calc.total_profit': '预计毛利润总额',
    'calc.convert_to_quotation': '一键生成正式报价单',
    'calc.convert_to_pi': '一键转为形式发票 (PI)',
    'calc.convert_to_ci': '一键转为商业发票 (CI)',

    // CBM & Container Loading Calculator
    'cbm.title': '集装箱装柜容积与装箱计算 (CBM)',
    'cbm.subtitle': '精准计算整柜出运总体积 (CBM)、总毛重 (KG)，智能模拟 20GP/40GP/40HQ/45HQ 装箱利用率与配载建议。',
    'cbm.add_item': '添加装箱货品行',
    'cbm.select_preset': '从产品库快速载入',
    'cbm.total_cbm': '总装运体积 (CBM)',
    'cbm.total_weight': '总货物毛重 (KG)',
    'cbm.total_cartons': '总外箱箱数 (Cartons)',
    'cbm.total_pcs': '出运产品总数 (PCS)',
    'cbm.container_fit': '各大柜型装载率分析',
    'cbm.fit_status': '装箱可行性与建议',
    'cbm.create_invoice': '以当前装箱数据生成商业发票',
    'cbm.create_packing': '以当前装箱数据生成装箱单',

    // Document Shared (Toolbar, Ledger & Editor)
    'doc.ledger_title': '单据台账与历史归档',
    'doc.create_new': '新建单据草稿',
    'doc.edit_doc': '编辑单据内容',
    'doc.print_pdf': '打印 / 导出 PDF',
    'doc.download_pdf': '下载 PDF',
    'doc.save_sync': '保存并同步云端',
    'doc.delete_doc': '删除单据',
    'doc.back_to_list': '返回单据列表',
    'doc.basic_details': '单据基础信息与参考号',
    'doc.invoice_number': '发票/单据编号',
    'doc.document_date': '开立日期',
    'doc.due_date': '有效/到期日期',
    'doc.payment_terms': '付款条款',
    'doc.delivery_terms': '贸易术语 / 交货条件',
    'doc.currency': '结算币种',
    'doc.seller_info': '发货人 / 出口商信息 (Shipper)',
    'doc.buyer_info': '收货人 / 买家信息 (Consignee)',
    'doc.items_table': '品名与商品明细表',
    'doc.item_desc': '商品英文品名及描述',
    'doc.item_sku': '产品型号/SKU',
    'doc.item_qty': '数量',
    'doc.item_unit': '单位',
    'doc.item_unit_price': '单价',
    'doc.item_total': '金额小计',
    'doc.subtotal': '商品货值合计',
    'doc.shipping_fee': '运费 (Freight)',
    'doc.insurance_fee': '保险费 (Insurance)',
    'doc.packaging_fee': '包装费 (Packaging)',
    'doc.discount': '贸易折扣 (Discount)',
    'doc.grand_total': '应收总计金额 (Grand Total)',
    'doc.notes_terms': '特殊条款与银行收汇指令',
    'doc.bank_details': '国际电汇 / SWIFT 银行信息',
    'doc.stamp_sign': '公司出口中英文公章与签名',
    'doc.copy_btn': '复制并新建此单据',

    // Specific Documents
    'doc.ci_title': '商业发票 (Commercial Invoice)',
    'doc.ci_desc': '出口报关结汇标准商业发票，支持自动汇率与金额大写转换、中英文公章及银行信息联动。',
    'doc.pi_title': '形式发票 (Proforma Invoice / PI)',
    'doc.pi_desc': '客户定金付款与国际外汇预付凭证，包含银行账户及定金条款。',
    'doc.quotation_title': '外贸正式报价单 (Sales Quotation)',
    'doc.quotation_desc': '外贸正规销售报价单，支持阶梯数量报价、有效期限及交货期明细。',
    'doc.packing_title': '装箱单 (Packing List / PL)',
    'doc.packing_desc': '海关清关与集装箱出运装箱明细表，自动统计净重、毛重、外箱尺寸与总体积。',
    'doc.contract_title': '国际售货合同 (Sales Contract / SC)',
    'doc.contract_desc': '中英文双语正规出口售货合同，包含国际商会仲裁条款、争议解决与不可抗力约定。',
    'doc.co_title': '原产地证明书 (Certificate of Origin / CO)',
    'doc.co_desc': '贸促会/海关标准原产地证格式，支持进口国关税减免与产地证明。',
    'doc.shipping_title': '出运订舱通知单 (Shipping Instructions)',
    'doc.shipping_desc': '货代订舱确认与装船指示，包含船名航次、卸货港及通知人信息。',
    'doc.sample_title': '免费样品发票 (Sample Commercial Invoice)',
    'doc.sample_desc': '国际快递 DHL / FedEx / UPS 清关专用无商业价值样品发票。',

    // Company Settings
    'settings.title': '公司抬头与出口档案设置',
    'settings.subtitle': '统一配置出口商英文抬头、海外收汇银行信息、中英文公章印章与透明签名。',
    'settings.save_success': '设置已成功保存并实时同步至云端 Firestore！',
    'settings.company_name': '出口商法定英文名称 (Company Name)',
    'settings.company_address': '出口商详细注册地址 (Address)',
    'settings.tax_id': '统一社会信用代码 / 税号 (Tax ID / USCC)',
    'settings.phone': '外贸联系电话 (Tel/Phone)',
    'settings.email': '官方联系邮箱 (Email)',
    'settings.website': '公司官网网址 (Website)',
    'settings.bank_info': '国际美金/跨境收汇银行信息 (Banking Instructions)',
    'settings.bank_name': '收款银行名称 (Beneficiary Bank)',
    'settings.account_name': '收款账户名称 (Account Name)',
    'settings.account_num': '收汇账号 / IBAN (Account / IBAN)',
    'settings.swift_code': '银行国际代码 (SWIFT Code)',
    'settings.bank_branch': '开户分行及详细地址 (Bank Branch & Address)',
    'settings.seal_signature': '官方公章、合同章与手写签名',
    'settings.stamp_label': '中英文双语条形/圆形发票公章',
    'settings.signature_label': '法定代表人/授权人手写透明签名',
    'settings.save_button': '保存并同步公司设置',
    'settings.reset_workspace': '恢复默认演示数据',

    // Common Buttons & Tooltips
    'btn.save': '保 存',
    'btn.cancel': '取 消',
    'btn.delete': '删 除',
    'btn.edit': '编 辑',
    'btn.create': '新建单据',
    'btn.print': '打印 / 导出 PDF',
    'btn.download_pdf': '下载 PDF',
    'btn.add_item': '添加产品品项',
    'btn.search': '搜 索',
    'btn.filter': '筛 选',
    'btn.close': '关 闭',
    'btn.back': '返 回',
    'btn.confirm': '确 定',
    'btn.copy': '复 制',
    'btn.copied': '已复制！',
    'btn.export': '导 出',
    'btn.import': '导 入',
    'btn.refresh': '刷 新',

    // Languages
    'lang.english': 'English',
    'lang.chinese': '中文 (简体)'
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string, defaultText?: string) => defaultText || key
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('waimao_app_language') as Language;
      if (saved === 'en' || saved === 'zh') return saved;
      // Auto detect user language preference
      if (typeof navigator !== 'undefined' && navigator.language) {
        if (navigator.language.startsWith('zh')) {
          return 'zh';
        }
      }
    } catch {
      // ignore
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('waimao_app_language', lang);
      document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
    } catch {
      // ignore
    }
  };

  useEffect(() => {
    try {
      document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en';
    } catch {
      // ignore
    }
  }, [language]);

  const t = (key: string, defaultText?: string): string => {
    const dict = translations[language] || translations.en;
    if (dict[key]) {
      return dict[key];
    }
    if (translations.en[key]) {
      return translations.en[key];
    }
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
